CFLAGS=-g -Wall -std=c11
LDLIBS=-lm

all: Przeciwprostokontna Silnia Liczby_Idealne tabliczka ZgadnijLiczbe odwracanie symbole

Przeciwprostokontna:Przeciwprostokontna.c

Silnia:Silnia.c

Liczby_Idealne:Liczby_Idealne.c

tabliczka:tabliczka.c

ZgadnijLiczbe:ZgadnijLiczbe.c

odwracanie:odwracanie.c

symbole:symbole.c

clean:
	rm -f Przeciwprostokontna Silnia Liczby_Idealne tabliczka ZgadnijLiczbe odwracanie symbole