CFLAGS=-g -Wall -std=c11
LDLIBS=-lm

all:2kwadrat szach porow lubelska parzyste tablica min_and_max 4figury

2kwadrat:2kwadrat.c

szach:szach.c

porow:porow.c

lubelska:lubelska.c

parzyste:parzyste.c

tablica:tablica.c

min_and_max:min_and_max.c

4figury:4figury.c

clean:
	rm -f a.out  2kwadrat szach porow lubelska parzyste tablica min_and_max 4figury


