CFLAGS=-g -Wall -std=c11
LDLIBS=-lm

all: ASCI_Conventer CmToInch AgeToSec SecOfLife

ASCI_Conventer:ASCI_Conventer.c

CmToInch:CmToInch.c

AgeToSec:AgeToSec.c

SecOfLife:SecOfLife.c

clean:
	rm -f ASCI_Conventer CmToInch AgeToSec SecOfLife